// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YousifsProject.Models.Entities;

#nullable disable

namespace YousifsProject.Migrations
{
    [DbContext(typeof(CityContext))]
    partial class CityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("YousifsProject.Models.Entities.House", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<bool>("HaveBalcony")
                        .HasColumnType("bit");

                    b.Property<bool>("HaveDoor")
                        .HasColumnType("bit");

                    b.Property<bool>("HaveWindow")
                        .HasColumnType("bit");

                    b.Property<int>("NumberOfFloors")
                        .HasColumnType("int");

                    b.Property<int>("RoofId")
                        .HasColumnType("int")
                        .HasColumnName("RoofID");

                    b.Property<int>("SortingOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoofId");

                    b.HasIndex(new[] { "Address" }, "UQ__Houses__7D0C3F321B2DCE52")
                        .IsUnique();

                    b.ToTable("Houses");
                });

            modelBuilder.Entity("YousifsProject.Models.Entities.Roof", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("TypeOfRoof")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Roofs");
                });

            modelBuilder.Entity("YousifsProject.Models.Entities.House", b =>
                {
                    b.HasOne("YousifsProject.Models.Entities.Roof", "Roof")
                        .WithMany("Houses")
                        .HasForeignKey("RoofId")
                        .IsRequired()
                        .HasConstraintName("FK__Houses__RoofID__49C3F6B7");

                    b.Navigation("Roof");
                });

            modelBuilder.Entity("YousifsProject.Models.Entities.Roof", b =>
                {
                    b.Navigation("Houses");
                });
#pragma warning restore 612, 618
        }
    }
}
